### PR TITLE
PLEASE FIX THIS! -.-

### PR DESCRIPTION
**Pull request by z3ntu**
:D #failed

### CODE REVIEW

**Comment by Xorok** [comment]
http://stackoverflow.com/questions/8194713/difference-between-java-javaw-javaws

#noyoufailed

**Comment by z3ntu** [comment]
```
luca@luca-G550JK:~$ javaw
No command 'javaw' found, but there are 23 similar ones
javaw: command not found`
```

#noyoustillfailed

**Comment by Xorok** [comment]
That's why I asked you. This works on Windows

**Comment by z3ntu** [comment]
But I made a pull request with a WORKING script and you changed it just because you thought what you did could work...?

**Pull request closed without merging**
